# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfeab27676795f7d6469f4758348c8f378d069465ebfcf5e5b1928ef47d70c5958af20a5015174de45a88cd46fa80d8ed7ce91e6e72ce7501534cc8d0d305de3

test:
  secret_key_base: 7fee1f4d1249b525d58649f175b90baddf46a7ec57a4e827a5a1b1dd81eed4a419589794e7948638d74069ad9ec1d0261780dbc41acc67fcc620b052ace6018f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
